export { RouterLink, RouterProvider } from './components';
export { useRouter } from './hooks';
export { RouterContext } from './lib';
export { BaseRouter } from './router';
export type {
  AfterNavigateHook,
  BlockedResult,
  BuildPathSearch,
  ErrorResult,
  InternalHistoryState,
  NavigateExternalOptions,
  NavigateOptions,
  NavigationBlockedHook,
  NavigationErrorHook,
  NavigationLocation,
  QueryParamConfig,
  RedirectResult,
  ResolvedResult,
  ResolvedRouteInfo,
  ResolvedRouteState,
  ResolveResult,
  RewriteResult,
  RouteConfig,
  RouteMiddleware,
  RouteMiddlewareContext,
  RouteMiddlewareResult,
  RouteParams,
  RouterOptions,
  RouterSnapshot,
  ScrollBehaviorFn,
  ScrollPosition,
  ScrollTarget,
  SearchParams,
  SearchParamsPatch,
  SearchParamValue,
  StateCompareStrategy,
} from './types';
export {
  addBase,
  applyQueryParamConfig,
  applyScrollTarget,
  buildPathByRoute,
  compareDeep,
  compareReference,
  compareShallow,
  defaultScrollBehavior,
  generateHistoryKey,
  getCurrentFullPath,
  getRouteScore,
  getWildcardParamName,
  handleResolveResult,
  isWildcardSegment,
  matchRoute,
  matchSegments,
  normalizeBase,
  normalizeFullPath,
  normalizeInputPath,
  normalizePath,
  parseUrl,
  rankRoutes,
  readHistoryState,
  resolveComparator,
  ResolveResultType,
  runMiddlewares,
  scheduleScrollToFragment,
  scrollToFragment,
  stripBase,
  validateParams,
  wrapState,
} from './utils';
